package automation.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.util.*;
public class AboutAccentureTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  
	WebDriverManager.chromedriver().setup();
		
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    setVars(new HashMap<String, Object>());
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aboutAccenture() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1280, 721));
    driver.findElement(By.name("q")).sendKeys("accenture");
    driver.findElement(By.name("q")).sendKeys(Keys.RETURN);
    //driver.findElement(By.xpath("//*[@id=\"tsf\"]/div[2]/div[1]/div[3]/center/input[1]")).click();
    //Getting all links present in search result
    List<WebElement> we = driver.findElements(By.xpath("//*[@id=\"search\"]//a"));
    //Clicking on the first link
    we.get(0).click();
    driver.findElement(By.xpath("//*[@id=\"onetrust-close-btn-container\"]/button")).click();
    driver.findElement(By.cssSelector("#footer-block > div > div > div > div > div.row.footer-links-container > div.col-xs-12.col-sm-6.col-md-8 > div > div:nth-child(4) > div > a")).click();
    driver.findElement(By.cssSelector(".reinvent-location-keywords")).sendKeys("Singapore");
    driver.findElement(By.cssSelector(".reinvent-location-button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".reinvent-location-search-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".contact-us-link > .contact-us")).click();
    String contact = driver.findElement(By.xpath("//*[@id=\"block-generalinq_1col\"]/div/div[2]/div/div[1]/div[2]/div")).getText();
    System.out.println("Contact Number : " + contact);
  }
public Map<String, Object> getVars() {
	return vars;
}
public void setVars(Map<String, Object> vars) {
	this.vars = vars;
}
}
